### Listar todos os filmes (GET)
GET http://localhost:3000/filmes

### Adicionar novo filme (POST)
POST http://localhost:3000/filmes
Content-Type: application/json

{
    "title": "Homem-Aranha: Sem Volta para Casa",
    "genre": "Ação",
    "duration": 148,
    "age_rating": "12"
}

### Editar filme (PUT)
PUT http://localhost:3000/filmes/1
Content-Type: application/json

{
    "title": "O Senhor dos Anéis (Versão Estendida)",
    "genre": "Fantasia",
    "duration": 201,
    "age_rating": "12"
}

### Apagar filme (DELETE)
DELETE http://localhost:3000/filmes/12